services:
  web:
    build: .
    ports:
      - "8485:8080"
    networks:
      - flask-play

  sqlite3:
    image: keinos/sqlite3:latest
    restart: unless-stopped
    networks:
      - flask-play
    tty: true
    volumes:
      - sqlite3-flask-play:/root/db/

  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - flask-play
#    ports:
#      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-flask-play:/data/db

  dbgate:
    image: dbgate/dbgate
    restart: unless-stopped
    networks:
      - flask-play
    ports:
      - "8486:3000"
    volumes:
      - dbgate-flask-play:/root/.dbgate
    environment:
      BASIC_AUTH: true
      LOGINS: admin
      LOGIN_PASSWORD_admin: admin
      CONNECTIONS: con1
      LABEL_con1: MongoDB
      URL_con1: mongodb://root:example@mongo:27017/
      ENGINE_con1: mongo@dbgate-plugin-mongo

networks:
  flask-play:
    driver: bridge

volumes:
  sqlite3-flask-play:
    external: true
  mongodb-flask-play:
    external: true
  dbgate-flask-play:
    external: true