services:
  nginx:
    build: nginx
    environment:
      - FLASK_SERVER_ADDR=flask:8080
    ports:
      - "8485:8080"
    command: /app/start.sh
    networks:
      - net

  flask:
    build: flask
    ports:
      - "8486:8080"
    networks:
      - net

  postgres:
    image: postgres:18-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: auth
      # POSTGRES_INITDB_ARGS – Sends arguments to postgres_initdb and adds functionality
      # POSTGRES_INITDB_WALDIR – Defines a specific directory for the Postgres transaction log.
      # POSTGRES_HOST_AUTH_METHOD – Controls the auth-method for host connections to all databases, users, and addresses
      # PGDATA – Defines another default location or subdirectory for database files
    networks:
      - net
    ports:
      - "5432:5432"
    volumes:
      - postgres-flask-play:/var/lib/postgresql/data

  mongo:
    image: mongo:8-noble
    restart: unless-stopped
    networks:
      - net
    #   ports:
    #     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-flask-play:/data/db
      - mongoconfigdb-flask-play:/data/configdb

  dbgate:
    image: dbgate/dbgate
    restart: unless-stopped
    networks:
      - net
    ports:
      - "8487:3000"
    volumes:
      - dbgate-flask-play:/root/.dbgate
    environment:
      BASIC_AUTH: true
      LOGINS: admin
      LOGIN_PASSWORD_admin: admin
      CONNECTIONS: con1,con2
      LABEL_con1: MongoDB
      URL_con1: mongodb://root:example@mongo:27017/
      ENGINE_con1: mongo@dbgate-plugin-mongo
      LABEL_con2: Postgres
      SERVER_con2: postgres
      USER_con2: root
      PASSWORD_con2: example
      PORT_con2: 5432
      ENGINE_con2: postgres@dbgate-plugin-postgres

networks:
  net:
    driver: bridge

volumes:
  postgres-flask-play:
    external: true
  mongodb-flask-play:
    external: true
  mongoconfigdb-flask-play:
    external: true
  dbgate-flask-play:
    external: true