# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.6.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-10-05T12:52:23Z"
  labels:
    app: flask-play-nginx-1-pod
  name: nginx
spec:
  containers:
  - args:
    - /app/start.sh
    env:
    - name: FLASK_SERVER_ADDR
      value: flask:8080
    image: docker.io/library/flask-play-nginx:latest
    name: nginx
    ports:
    - containerPort: 8080
      hostPort: 8485
    securityContext: {}
